### ISSUE TITLE
Replace() or Remove()

### ISSUE THREAD

**Issue by nyarly** [samsalisbury/psyringe#3]
While catching double-additions is very useful for error detection purposes, for testing, it would be useful to be able to override a particular injection - a method like Replace() on Psyringe would be handy as a way to do near-integration tests.

**Comment by samsalisbury** [comment]
I would consider a PR adding this, although I tend to prefer not to add it as it will expand the interface and I think it will tend to lead to less precise code if used outside of a test scanario. Closing for now, but feel free to reopen if you think it needs more consideration.
