### ISSUE TITLE
Conflicting ctors leads to indeterminate state.

### ISSUE THREAD

**Issue by nyarly** [samsalisbury/psyringe#8]
Just discovered this:

https://github.com/opentable/sous/blob/ab17fbb8034bd093ccb71bbc18604eddad5fa8cd/graph/testsupport.go#L30

I would expect that line to panic, because it adds a ctor for `*ConfigLoader`, but the psyringe returned by `BuldBaseGraph` already has a ctor for `*ConfigLoader`. Instead, which is chosen appears to be non-deterministic.

**Comment by samsalisbury** [comment]
Hmm, doesn't look good, thanks for the report, will need to add test case for this, I thought this was already covered by https://github.com/samsalisbury/psyringe/blob/master/psyringe_add_test.go#L38 but we should add test cases for pointers to structs as well.

**Comment by samsalisbury** [comment]
This was fixed in https://github.com/samsalisbury/psyringe/commit/afa419dfe20cdfb9c1ed69eb5ea6e400f32954ec
